CREATE TABLE IF NOT EXISTS payment_events (
event_id INT AUTO_INCREMENT PRIMARY KEY,
amount DECIMAL(12,2) NOT NULL,
event_date DATETIME NOT NULL,
odoo_move_id INT NULL,
sync_status ENUM('PENDING','COMPLETED','FAILED') NOT NULL DEFAULT 'PENDING',
error_text TEXT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);